name: CI

on:
  pull_request:
    branches:
      - main  # Change this to your default branch if different
      - RC-v*
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run js-lint  # Change this to your lint script name

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test  # Change this to your test script name
